# Generated by Django 4.1.2 on 2023-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0002_alter_formulario_jornada_alter_formulario_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='jornada',
            field=models.IntegerField(choices=[[0, 'Jornada Completa'], [1, '1/2 Jornada'], [2, '1/4 Jornada']], default='Jornada Completa', max_length=100),
        ),
    ]
