# Generated by Django 4.1.2 on 2023-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0003_alter_formulario_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='jornada',
            field=models.IntegerField(choices=[[0, 'Jornada Completa'], [1, '1/2 Jornada'], [2, '1/4 Jornada']], default='Jornada Completa'),
        ),
    ]
