# Generated by Django 4.1.2 on 2023-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0005_alter_formulario_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(default='dias_administrativo@cslb.cl', max_length=254),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Denegado'], [1, 'Aprobado'], [2, 'pendiente']], default=2),
        ),
    ]
