# Generated by Django 4.1.2 on 2023-10-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0006_alter_formulario_email_alter_formulario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='dias_restantes',
            field=models.PositiveIntegerField(default=3, verbose_name='Días Restantes'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='jornada',
            field=models.IntegerField(choices=[[1, 'Jornada Completa'], [0.5, '1/2 Jornada'], [0.25, '1/4 Jornada']], default='Jornada Completa'),
        ),
    ]
