# Generated by Django 4.1.2 on 2023-10-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0007_formulario_dias_restantes_alter_formulario_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='dias_restantes',
        ),
        migrations.AddField(
            model_name='user',
            name='dias_restantes',
            field=models.PositiveIntegerField(default=3, verbose_name='Días Restantes'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Denegado'], [1, 'Aprobado'], [2, 'pendiente'], [3, 'Tomado']], default=2),
        ),
    ]
