# Generated by Django 4.1.2 on 2023-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0008_remove_formulario_dias_restantes_user_dias_restantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dias_cumpleaños',
            field=models.PositiveIntegerField(default=1, verbose_name='Días cumpleaños'),
        ),
    ]
