# Generated by Django 4.1.2 on 2023-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0009_user_dias_cumpleaños'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
