# Generated by Django 4.1.2 on 2023-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0011_remove_formulario_bloqueado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dias_restantes',
        ),
        migrations.AddField(
            model_name='user',
            name='dias_tomados',
            field=models.PositiveIntegerField(default=0, verbose_name='Días Tomados'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Denegado'], [1, 'Aprobado'], [2, 'pendiente'], [3, 'Tomado'], [4, 'No Tomado']], default=2),
        ),
    ]
