# Generated by Django 4.1.2 on 2023-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0012_remove_user_dias_restantes_user_dias_tomados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dias_Restantes',
            field=models.PositiveIntegerField(default=3, verbose_name='Días Restantes'),
        ),
    ]
