# Generated by Django 4.1.2 on 2023-10-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0013_user_dias_restantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dias_Restantes',
            new_name='dias_restantes',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='jornada',
            field=models.DecimalField(choices=[[1, 'Jornada Completa'], [0.5, '1/2 Jornada'], [0.25, '1/4 Jornada']], decimal_places=2, default='Jornada Completa', max_digits=2),
        ),
    ]
