# Generated by Django 4.1.2 on 2023-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0015_alter_formulario_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dias_restantes',
            field=models.FloatField(default=3, verbose_name='Días Restantes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dias_tomados',
            field=models.FloatField(default=0, verbose_name='Días Tomados'),
        ),
    ]
