# Generated by Django 4.1.2 on 2023-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0016_alter_user_dias_restantes_alter_user_dias_tomados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dias_cumpleaños',
            field=models.FloatField(default=1, verbose_name='Días cumpleaños'),
        ),
    ]
