# Generated by Django 4.1.2 on 2023-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0018_user_bloqueado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bloqueado',
        ),
        migrations.AddField(
            model_name='formulario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
