# Generated by Django 4.1.2 on 2023-10-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0019_remove_user_bloqueado_formulario_bloqueado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='bloqueado',
        ),
    ]
