# Generated by Django 4.1.2 on 2023-10-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0020_remove_formulario_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.IntegerField(default=5),
        ),
    ]
