# Generated by Django 4.1.2 on 2023-10-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0021_user_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grupo',
            new_name='group_id',
        ),
    ]
