# Generated by Django 4.1.2 on 2023-10-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0022_rename_grupo_user_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_id',
        ),
    ]
