# Generated by Django 4.1.2 on 2023-10-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0025_formulario_encargado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
