# Generated by Django 4.1.2 on 2023-10-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0026_user_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='encargado_id',
        ),
    ]
