# Generated by Django 4.1.2 on 2023-10-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0027_rename_group_id_user_encargado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='encargado_id',
            new_name='grupo_encargado_id',
        ),
    ]
