# Generated by Django 4.1.2 on 2023-10-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0028_rename_encargado_id_user_grupo_encargado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jefe_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
