# Generated by Django 4.1.2 on 2023-10-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0029_user_jefe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo_encargado_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jefe_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
