# Generated by Django 4.1.2 on 2023-10-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0031_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
