# Generated by Django 4.1.2 on 2023-10-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0034_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='c_re_sociales',
        ),
    ]
