# Generated by Django 4.1.2 on 2023-10-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0036_social_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='social_account',
        ),
    ]
