# Generated by Django 4.1.2 on 2023-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0037_delete_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dias_restantes',
            field=models.FloatField(default=2, verbose_name='Días Restantes'),
        ),
    ]
